language: go

go:
  - 1.13.x

before_install:
  - npm install -g @vue/cli@latest
  - GO111MODULE=off go get github.com/markbates/pkger/cmd/pkger
  - ${GO_PATH}/bin/pkger -h

before_deploy:
  - "GOOS=linux GOARCH=amd64 make && tar czf mego-linux.tar.gz mego-api/mego && rm -rf mego-api/mego"
  - "GOOS=darwin GOARCH=amd64 make && tar czf mego-mac.tar.gz mego-api/mego && rm -rf mego-api/mego"
  - "GOOS=windows GOARCH=amd64 make && tar czf mego-win.tar.gz mego-api/mego.exe && rm -rf mego-api/mego.exe"

deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file:
    - "mego-linux.tar.gz"
    - "mego-win.tar.gz"
    - "mego-mac.tar.gz"
  skip_cleanup: true
  on:
    tags: true
